version: "3.8"
services:
  redisOfficial:
    image: 'docker.io/bitnami/redis'
    container_name: 'Redis'
    restart: unless-stopped
    environment:
      ALLOW_EMPTY_PASSWORD: "yes" # redis anomymous mode
      REDIS_AOF_ENABLED: "no"
    ports:
      - "6379:6379"
      
  rabbitmqOfficial:
   image: rabbitmq:management-alpine
   container_name: 'RabbitMQ'
   restart: unless-stopped
   volumes:
    - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
    - ./definitions.json:/etc/rabbitmq/definitions.json:ro
   ports:
    - 5672:5672 # AMQP protocol port
    - 15672:15672 # HTTP management UI user:admin pw:admin
    
  ListenerAPI:
    image: bpmonline/exchangelistener:0.8.74 # Latest Listener version available here https://hub.docker.com/r/bpmonline/exchangelistener/tags?page=1&ordering=last_updated
    container_name: 'ListenerAPI'
    restart: unless-stopped
    ports:
      - 10000:80 # Port forward. External port:local port
    environment:
      ExchangeListenerRedisHost: redisOfficial:6379 # Redis connection
      ExchangeListenerRedisDatabase: 0 # Redis DB
      PodName: ExchangeListener
    depends_on:
      - redisOfficial
      - rabbitmqOfficial
    volumes:
     - ./appsettings.json:/app/config/appsettings.json:ro
     - ./appsettingsrmq.json:/app/config/rabbitmq.secrets.json:ro
      
  ListenerWorker:
    image: bpmonline/exchangelistener-worker:0.8.74 # Latest Listener version available here https://hub.docker.com/r/bpmonline/exchangelistener/tags?page=1&ordering=last_updated
    container_name: 'ListenerWorker'
    restart: unless-stopped
    environment:
      ExchangeListenerRedisHost: redisOfficial:6379 # Redis connection
      ExchangeListenerRedisDatabase: 0 # Redis DB
      PodName: ExchangeListenerWorker
    depends_on:
      - redisOfficial
      - rabbitmqOfficial
    volumes:
     - ./appsettings.json:/app/appsettings.json:ro
     - ./appsettingsrmq.json:/app/appsettings.Production.json:ro

